name: PvPBot
version: 1.1.5
main: com.pvpbot.PvPBotPlugin
api-version: '1.21'
depend:
  - voicechat
commands:
  pvpbot:
    permission: pvpbot.admin
    description: PvP Bot commands
    usage: /pvpbot <spawn|spawnrandom|masspawn|masspawnrandom|portals|settings|remove|removeall|list|difficulty|kit|faction|give|farm|checkchest> - see /pvpbot for full syntax
permissions:
  pvpbot.admin:
    description: Access to all PvPBot commands
    default: op
